import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

"""

select cust, prod, avg(quant), max(quant) 
from sales
where year=2017  
group by cust, prod

{
'select': ['cust', 'prod', 'avg(quant)', 'max(quant)'], 
'no_group_var': 0, 
'group_attribute': ['cust', 'prod'], 
'agg_functions': ['1_avg_quant', '1_max_quant'], 
'predicates': ['year=2017'], 
'having': ['NONE']
}
"""

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []

    groupby= {}
    # Table Scan 1: Get the value of 
    for row in cur:
        if row['year'] == 2017:
            key = row['cust'] + ','+ row['prod']
            if key not in groupby:
                groupby[key] = [ row['quant'] ]
            else:
                groupby[key].append(row['quant'])
            
    
    for key in groupby:
        all_values = groupby[key]
        avg_quant = sum(all_values) / len(all_values)
        max_quant = max(all_values)
        _global.append({'cust': key.split(',')[0], 'prod': key.split(',')[1], 'avg_quant': avg_quant, 'max_quant': max_quant})

    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    