
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
from helpers import update_agg_value

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    data = cur.fetchall()
    
    _global = []
    
    # Step 1: Gather unique "groupby"s (mf_struct)
    groupby = {}
    for row in data:
        key = str(row['cust']) + "," +str(row['month'])
        if key not in groupby:
            groupby[key] = {
                 '0_avg_quant' : [0,0],
                 '1_avg_quant' : [0,0],
                 '2_avg_quant' : [0,0],
                
            }
        else:
            pass
    # Step 2: Instead of one pass, this is now based on the number of grouping variables.
    # Iterate through and check predicates.
    
    for row in data:
        grouping_attr = str(row['cust']) + "," +str(row['month'])
        if row['year'] == 2018:
            for key in groupby:
                grouping_var = 0 
                grouping_attrs = key.split(',')
                for item in grouping_attrs:
                    if item.isnumeric():
                        grouping_attrs[grouping_attrs.index(item)] = int(item)
                # Generated code as seen in helper.py methods.
                item_cust = grouping_attrs[0]
                item_month = grouping_attrs[1]
                
                if item_cust == row['cust'] and item_month == row['month']:
                    grouping_var = 0
                else:
                    continue
                change_group = groupby[key]
                update_agg_value(change_group, grouping_var, row)
            
    for row in data:
        grouping_attr = str(row['cust']) + "," +str(row['month'])
        if row['year'] == 2018:
            for key in groupby:
                grouping_var = 0 
                grouping_attrs = key.split(',')
                for item in grouping_attrs:
                    if item.isnumeric():
                        grouping_attrs[grouping_attrs.index(item)] = int(item)
                # Generated code as seen in helper.py methods.
                item_cust = grouping_attrs[0]
                item_month = grouping_attrs[1]
                
                if row['cust'] ==  item_cust  and row['month'] <  item_month :
                    grouping_var = 1
                else:
                    continue
                change_group = groupby[key]
                update_agg_value(change_group, grouping_var, row)
            
    for row in data:
        grouping_attr = str(row['cust']) + "," +str(row['month'])
        if row['year'] == 2018:
            for key in groupby:
                grouping_var = 0 
                grouping_attrs = key.split(',')
                for item in grouping_attrs:
                    if item.isnumeric():
                        grouping_attrs[grouping_attrs.index(item)] = int(item)
                # Generated code as seen in helper.py methods.
                item_cust = grouping_attrs[0]
                item_month = grouping_attrs[1]
                
                if row['cust'] ==  item_cust  and row['month'] >  item_month :
                    grouping_var = 2
                else:
                    continue
                change_group = groupby[key]
                update_agg_value(change_group, grouping_var, row)
            
    # Step 3: Revise averages, just like in an MF Query
    for grouping_attr_key, grouping_attr in groupby.items():
        for agg_func_key, agg_func in grouping_attr.items():
            if 'avg' in agg_func_key:
                avg_list = groupby[grouping_attr_key][agg_func_key]
                if avg_list[1] == 0:
                    groupby[grouping_attr_key][agg_func_key] = 0
                else:
                    groupby[grouping_attr_key][agg_func_key] = avg_list[0]/avg_list[1] 
    # Step 4: Filter out table using the having clause.
        if True:
            _global.append({ 'cust,month': grouping_attr_key,'0_avg_quant':groupby[grouping_attr_key]['0_avg_quant'],'1_avg_quant':groupby[grouping_attr_key]['1_avg_quant'],'2_avg_quant':groupby[grouping_attr_key]['2_avg_quant'],})
        
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    